name: Docker Build

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 0 * * 0'  # Запускать каждое воскресенье в полночь UTC
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t pzhukov/ansible-runner:latest .

    - name: Push Docker Image
      run: docker push pzhukov/ansible-runner:latest
